### PR TITLE
extend string utils tests

### PR DESCRIPTION
**Pull request by thedavidmeister**
WIP, extending tests while learning how login works

### CODE REVIEW

**Comment by tonyofbyteball** [comment]
Please keep it focused, the diff is huge and there are lots of unrelated whitespace changes

**Comment by thedavidmeister** [comment]
@tonyofbyteball please add a trailing whitespace tool to your IDE :P

**Comment by tonyofbyteball** [comment]
never, I don't like when something silently edits my code without my knowledge :)

**Comment by thedavidmeister** [comment]
whelp... here we are with a giant diff...

do you really want me to put those random whitespaces _back in_?

**Comment by tonyofbyteball** [comment]
yes please just copy the old versions of these files from master
otherwise someone working on another fork might hit unexpected conflicts

**Comment by thedavidmeister** [comment]
sorry, I'm not doing that because it is a waste of time

any merge conflicts would be beyond trivial to resolve, this is a contrived problem

what is going on here?

i'm offering working tests for critical path functionality and you're bike shedding me on useless whitespace cruft that any linter would have flagged long ago

**Comment by tonyofbyteball** [comment]
included in https://github.com/byteball/ocore/pull/245

**Pull request closed without merging**
